[deps]
FreeParaxialPropagation = "34432e42-2548-414e-b0ee-13347938ede4"
KerrPropagation = "44e0b942-886d-4477-aed0-6c177c249ffb"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
